/**
 * The section library: ready page sections in templates/library/sections, written in FlowCode's own React and
 * design-token CSS (templates/library/library.css). Each takes on a project's colors, fonts, spacing and corners
 * from its tokens. The Components page browses them; builds copy the ones a screen needs.
 */
export type SectionCategory = "navigation" | "hero" | "features" | "stats" | "pricing" | "testimonials" | "faq" | "cta" | "team" | "contact" | "newsletter" | "blog" | "footer" | "forms" | "tables" | "cards" | "dialogs" | "alerts" | "backgrounds" | "data" | "auth" | "wayfinding" | "homepages" | "landings" | "sites" | "apptemplates" | "commerce" | "neobrutal" | "kit";

export interface LibrarySection {
  /** File stem in templates/library/sections. */
  id: string;
  name: string;
  category: SectionCategory;
  description: string;
  /** Words a request or spec uses when this section fits. */
  tags: string[];
  /**
   * The kinds of screen or feature this pattern serves, in the words a PRD would use ("order history", "attendance",
   * "time off requests"). FlowCode matches the PRD's screens against them, and the library index shows them to agents.
   */
  useCases?: string[];
  /**
   * The jobs people do with it, in their own words ("decide on a request", "see what happened on a day"). FlowCode
   * matches them against what each planned screen is for (the user's intent), and agents see them in the library index.
   */
  jobs?: string[];
}

/** "template": whole pages, built from the library's own pieces. "page": marketing and website sections. "app": the
 * pieces an app's own screens are made of. */
export type SectionGroup = "template" | "page" | "app";

export const SECTION_CATEGORIES: Array<{ id: SectionCategory; label: string; group: SectionGroup }> = [
  { id: "homepages", label: "Homepages", group: "template" },
  { id: "landings", label: "Landing pages", group: "template" },
  { id: "sites", label: "Industry sites", group: "template" },
  { id: "apptemplates", label: "App screens", group: "template" },
  { id: "navigation", label: "Navigation", group: "page" },
  { id: "hero", label: "Heroes", group: "page" },
  { id: "features", label: "Features", group: "page" },
  { id: "stats", label: "Stats", group: "page" },
  { id: "pricing", label: "Pricing", group: "page" },
  { id: "testimonials", label: "Testimonials", group: "page" },
  { id: "faq", label: "FAQ", group: "page" },
  { id: "cta", label: "Calls to action", group: "page" },
  { id: "team", label: "Team", group: "page" },
  { id: "contact", label: "Contact", group: "page" },
  { id: "newsletter", label: "Newsletter", group: "page" },
  { id: "blog", label: "Blog", group: "page" },
  { id: "footer", label: "Footers", group: "page" },
  { id: "commerce", label: "Shop", group: "page" },
  { id: "backgrounds", label: "Page backgrounds", group: "page" },
  { id: "auth", label: "Sign-in and sign-up", group: "app" },
  { id: "wayfinding", label: "Tabs, breadcrumbs and paging", group: "app" },
  { id: "forms", label: "Forms", group: "app" },
  { id: "tables", label: "Tables and lists", group: "app" },
  { id: "cards", label: "Cards", group: "app" },
  { id: "dialogs", label: "Dialogs and drawers", group: "app" },
  { id: "alerts", label: "Alerts and states", group: "app" },
  { id: "data", label: "Charts and data", group: "app" },
  { id: "kit", label: "Small components", group: "app" },
  { id: "neobrutal", label: "Neobrutalism kit", group: "app" },
];

export const LIBRARY_SECTIONS: LibrarySection[] = [
  { id: "navbar-simple", name: "Simple navigation", category: "navigation", description: "Brand, page links and one main action; links fold into a menu on phones.", tags: ["header", "navbar", "menu", "navigation"], useCases: ["site header","marketing navigation","landing page header","product site menu","top navigation","mobile menu","saas homepage header"], jobs: ["find my way around the site","get to the page i need","start a free trial from anywhere","open the menu on my phone"] },
  { id: "navbar-centered", name: "Centered navigation", category: "navigation", description: "Links in the middle: a calmer header for content sites and studios.", tags: ["header", "navbar", "portfolio", "studio"], useCases: ["portfolio header","studio website header","blog header","editorial navigation","agency site menu","restaurant site header","content site navigation"], jobs: ["browse the main sections of the site","find the work or articles i want","get in touch with the studio","move between pages easily"] },
  { id: "hero-split", name: "Split hero", category: "hero", description: "Promise and actions beside a picture of the product.", tags: ["hero", "landing", "header", "product"], useCases: ["landing page hero","product launch","homepage intro","saas homepage","app download page","feature announcement","service landing page"], jobs: ["understand what the product does","see the product before signing up","start a free trial","decide if this is for me"] },
  { id: "hero-centered", name: "Centered hero", category: "hero", description: "One bold promise in the middle with a wide picture underneath.", tags: ["hero", "landing", "launch", "app"], useCases: ["landing page hero","product launch","app homepage","event announcement","coming soon page","campaign page","startup homepage"], jobs: ["understand the main promise quickly","see what the product looks like","get started right away","learn more before committing"] },
  { id: "hero-stats", name: "Hero with proof", category: "hero", description: "Promise and actions with three numbers that back it up.", tags: ["hero", "landing", "results", "stats"], useCases: ["landing page hero","results-driven homepage","agency homepage","fundraising page","b2b product homepage","case study intro","nonprofit impact page"], jobs: ["see proof the product works","judge whether the claims are credible","get started with confidence","book a demo with the team"] },
  { id: "features-grid", name: "Feature grid", category: "features", description: "Six benefits as cards, each with an icon, title and one sentence.", tags: ["features", "benefits", "services", "grid"], useCases: ["feature overview","benefits section","services list","product capabilities","why choose us","agency services","platform highlights","integrations overview"], jobs: ["see what the product can do","check it covers my needs","compare benefits at a glance","understand what services are offered"] },
  { id: "features-alternating", name: "Alternating features", category: "features", description: "Each feature with a picture and a short story, alternating sides.", tags: ["features", "how it works", "steps", "showcase"], useCases: ["how it works","product tour","feature showcase","step by step guide","onboarding overview","case study story","service process"], jobs: ["understand how the product works","see each feature in action","follow the process step by step","picture using it in my day"] },
  { id: "features-checklist", name: "Feature checklist", category: "features", description: "A heading beside a two-column list of what's included.", tags: ["features", "included", "checklist", "plan"], useCases: ["what's included","plan features","membership benefits","package contents","service inclusions","course syllabus","subscription perks"], jobs: ["see everything that's included","check a must-have feature is covered","know what i get for the price","decide whether to sign up"] },
  { id: "stats-band", name: "Stats band", category: "stats", description: "Four numbers on the accent color, a strong break between sections.", tags: ["stats", "numbers", "results", "metrics"], useCases: ["results section","company milestones","impact numbers","social proof metrics","about us figures","nonprofit impact","growth highlights"], jobs: ["see the results in numbers","judge how established the company is","trust the product with proof","understand the scale of impact"] },
  { id: "pricing-tiers", name: "Three pricing tiers", category: "pricing", description: "Three plans with the usual choice highlighted.", tags: ["pricing", "plans", "subscription", "tiers"], useCases: ["pricing page","subscription plans","plan comparison","membership tiers","saas pricing","service packages","course pricing"], jobs: ["find the right plan for my budget","compare plans side by side","see what the popular plan includes","choose a plan and sign up"] },
  { id: "pricing-toggle", name: "Monthly or yearly pricing", category: "pricing", description: "Two plans with a switch that shows the yearly saving.", tags: ["pricing", "plans", "yearly", "monthly", "subscription"], useCases: ["pricing page","subscription plans","monthly vs yearly billing","membership pricing","saas pricing","annual discount offer"], jobs: ["see how much i save yearly","pick monthly or yearly billing","choose between two plans","find the right plan for my budget"] },
  { id: "testimonials-cards", name: "Testimonial cards", category: "testimonials", description: "Three short quotes with who said them.", tags: ["testimonials", "reviews", "quotes", "social proof"], useCases: ["customer testimonials","reviews section","social proof","client feedback","success stories","user quotes","student reviews"], jobs: ["hear from people who use it","trust the product before buying","see whether people like me benefit","read honest customer feedback"] },
  { id: "testimonial-feature", name: "Featured quote", category: "testimonials", description: "One strong quote, centered, with who said it.", tags: ["testimonial", "quote", "review"], useCases: ["featured testimonial","customer quote","client endorsement","case study quote","founder quote","press quote"], jobs: ["hear a trusted customer's opinion","feel confident about choosing this","see a real success story"] },
  { id: "faq-accordion", name: "FAQ accordion", category: "faq", description: "Questions that open in place; works with the keyboard and without script.", tags: ["faq", "questions", "help", "accordion"], useCases: ["faq","help center","common questions","pricing questions","support page","product questions","shipping and returns","policy questions"], jobs: ["get an answer without contacting support","find out how billing works","clear up doubts before buying","find the answer to my question"] },
  { id: "faq-columns", name: "FAQ columns", category: "faq", description: "Every short answer visible at once, with a way to reach a person.", tags: ["faq", "questions", "help"], useCases: ["faq","common questions","help page","pricing questions","support page","quick answers"], jobs: ["scan all the answers at once","get an answer without contacting support","reach a person when stuck","clear up doubts before buying"] },
  { id: "cta-banner", name: "Call-to-action banner", category: "cta", description: "A closing invitation on the accent color with one main action.", tags: ["cta", "call to action", "sign up", "closing"], useCases: ["closing call to action","sign up prompt","free trial invite","demo request","end of page invite","download prompt","join waitlist"], jobs: ["get started now","sign up for a free trial","take the next step","book a demo"] },
  { id: "cta-split", name: "Call-to-action card", category: "cta", description: "An invitation in a card with a picture beside it.", tags: ["cta", "call to action", "import", "trial"], useCases: ["trial invite","data import prompt","upgrade prompt","download app","demo request","promotional offer","migration invite"], jobs: ["start a free trial","bring my data over easily","try the product with my own work","take the next step"] },
  { id: "team-grid", name: "Team grid", category: "team", description: "The people behind the product, with a role and one line each.", tags: ["team", "about", "people", "staff"], useCases: ["team page","about us","meet the team","staff directory","leadership","our people","board members","speakers"], jobs: ["see who is behind the product","find the right person to contact","trust the company by knowing the people","learn what each person does"] },
  { id: "contact-split", name: "Contact details and form", category: "contact", description: "Ways to reach you beside a short form that confirms and keeps the message.", tags: ["contact", "form", "email", "support", "address"], useCases: ["contact page","support form","get in touch","sales inquiry","office address","booking inquiry","customer support"], jobs: ["get in touch with the team","send a question to support","find the office address or phone","ask sales about a plan"] },
  { id: "newsletter-inline", name: "Newsletter sign-up", category: "newsletter", description: "One email field and a button, with a confirmation.", tags: ["newsletter", "subscribe", "email", "updates"], useCases: ["newsletter signup","email subscribe","product updates signup","waitlist","blog subscribe","launch notification","mailing list"], jobs: ["get updates by email","hear about the launch first","subscribe to new articles","join the waitlist"] },
  { id: "blog-cards", name: "Latest posts", category: "blog", description: "Three post cards with a picture, topic, title, summary and date.", tags: ["blog", "posts", "articles", "journal", "news"], useCases: ["blog","latest posts","news","articles","journal","resources","case studies","press releases","recipes"], jobs: ["read the latest articles","find posts on a topic i care about","keep up with company news","learn from guides and stories"] },
  { id: "footer-columns", name: "Footer with columns", category: "footer", description: "Brand and a line about it, three columns of links and the small print.", tags: ["footer", "links", "site map"], useCases: ["site footer","site map","marketing footer","company links","legal links","resource links"], jobs: ["find a page i couldn't find above","read the privacy policy or terms","get in touch or follow on social","browse every section of the site"] },
  { id: "footer-simple", name: "Simple footer", category: "footer", description: "One row: brand, a few links and the small print.", tags: ["footer", "app"], useCases: ["app footer","simple footer","landing page footer","legal links","small print"], jobs: ["read the privacy policy or terms","find a few key links","see who runs the site"] },
  { id: "alert-inline", name: "Inline alerts", category: "alerts", description: "Inline messages in info, success, warning and error tones, each with an icon, title, text and an optional action; dismissible ones close and can be brought back.", tags: ["alert","message","notice","status","feedback","dismissible"], useCases: ["form errors","success message","warning notice","system status","account notices","payment failed","validation feedback","info message"], jobs: ["know what went wrong and fix it","confirm my change was saved","notice something that needs my attention","dismiss a message i've read"] },
  { id: "banner-top", name: "Top announcement banner", category: "alerts", description: "Full-width announcement bar at the top of a page with a link and a dismiss button that remembers the dismissal.", tags: ["banner","announcement","notice","dismissible"], useCases: ["announcement bar","promo banner","new feature announcement","maintenance notice","sale announcement","cookie or policy notice","event promotion"], jobs: ["hear about what's new","find out about a sale or offer","learn about planned downtime","hide a notice i've seen"] },
  { id: "toast-stack", name: "Toast notifications", category: "alerts", description: "Toasts that stack bottom-right, auto-dismiss with a pause on hover or focus, close by hand or Escape, are announced to screen readers, and offer Undo.", tags: ["toast","snackbar","notification","undo"], useCases: ["notifications","save confirmation","undo action","background task updates","activity alerts","error notifications","upload complete"], jobs: ["know my action worked","undo something i did by mistake","stay aware of updates while working","notice errors without losing my place"] },
  { id: "empty-state", name: "Empty list state", category: "alerts", description: "An empty list with a small token-coloured drawing, helpful text and a primary action that adds the first item.", tags: ["empty state","list","onboarding","zero data"], useCases: ["empty list","first run","no projects yet","empty inbox","no tasks","empty cart","onboarding start","no saved items"], jobs: ["add my first item","understand what goes here","get started with the product","know what to do next"] },
  { id: "page-not-found", name: "404 page", category: "alerts", description: "Page-not-found screen with a big 404, a short message, a search over the main pages and links back.", tags: ["404","not found","error page"], useCases: ["404 page","page not found","broken link","missing page","error page"], jobs: ["find the page i was looking for","get back to the home page","search for what i need"] },
  { id: "card-product-grid", name: "Product card grid", category: "cards", description: "Shop product cards with a picture, name, price and rating, and an add-to-basket button that switches to Added and updates a basket count.", tags: ["shop","product","ecommerce","basket","cart","grid"], useCases: ["product catalog","online shop","store front","product listing","category page","menu items","marketplace listings","merch store"], jobs: ["browse products and prices","add items to my basket","compare products by rating","find something to buy"] },
  { id: "card-kpi", name: "KPI cards", category: "cards", description: "Dashboard number cards with the change on the last period (green or red by whether up is good) and a small trend line, with a week or month switch.", tags: ["dashboard","kpi","metrics","analytics","overview"], useCases: ["dashboard overview","kpi summary","analytics dashboard","sales metrics","admin overview","business performance","finance summary","store stats"], jobs: ["see how the business is doing","spot whether numbers are up or down","compare this week with last week","check key metrics at a glance"] },
  { id: "card-profile", name: "Profile card", category: "cards", description: "A person card with initials, role, short bio and three numbers, a Follow toggle and a Message button that opens a short note form.", tags: ["profile","person","contact","follow","avatar"], useCases: ["user profile","creator profile","team member card","contact card","author bio","mentor profile","freelancer profile","social profile"], jobs: ["learn about a person","follow someone i'm interested in","send someone a message","see someone's activity numbers"] },
  { id: "card-media-list", name: "Media list cards", category: "cards", description: "Wide cards with a picture on the left, title, summary, details and tags, a heart to save each one, and a switch to show only saved items.", tags: ["list","media","listing","favorites","saved"], useCases: ["listings","property listings","course catalog","event list","recipe list","job listings","saved items","travel destinations","podcast episodes"], jobs: ["browse listings with details","save items to come back to","see only my saved items","find the one that fits me"] },
  { id: "table-sortable", name: "Sortable table", category: "tables", description: "A clean data table with a caption, click-to-sort column headers, tabular numbers and a total row.", tags: ["table","sort","data","numbers"], useCases: ["data table","report table","sales report","leaderboard","budget breakdown","price list","inventory list","expense report"], jobs: ["sort data to find the highest values","compare figures across rows","see the total at a glance","review numbers in a report"] },
  { id: "table-actions", name: "Table with row actions", category: "tables", description: "A searchable, paginated table with status badges and a per-row menu to edit, duplicate or delete (with a confirmation).", tags: ["table","search","pagination","admin","status"], useCases: ["admin table","user management","order management","bookings list","invoice list","inventory management","customer list","content management"], jobs: ["find a record quickly","edit or remove an entry","check the status of each order","manage records page by page"] },
  { id: "table-selectable", name: "Selectable table", category: "tables", description: "A table with row checkboxes, select-all with a mixed state, and a bulk-action bar to mark done or delete, with undo.", tags: ["table","checkbox","select","bulk actions","undo"], useCases: ["bulk actions","task list","inbox management","order processing","admin table","file manager","user management","moderation queue"], jobs: ["handle many items at once","mark several tasks as done","delete items in bulk","undo a bulk change"] },
  { id: "list-stacked", name: "Stacked list", category: "tables", description: "A phone-friendly stacked list with initials, title, meta line, status and chevron, plus search, status filters and expandable rows.", tags: ["list","mobile","search","filter"], useCases: ["contact list","team members","order list","inbox","search results","file list","patient list","ticket list","mobile list"], jobs: ["find a person or item quickly","filter by status","see details without leaving the list","check what needs attention"] },
  { id: "dialog-confirm", name: "Confirm dialog", category: "dialogs", description: "A destructive confirmation (Delete this booking?) with Cancel focused first and a danger-coloured confirm, then a result message with Undo.", tags: ["dialog","modal","confirm","delete","undo"], useCases: ["delete confirmation","cancel booking","remove item","discard changes","destructive action","cancel subscription","archive confirmation"], jobs: ["avoid deleting something by mistake","confirm i really want to cancel","undo a deletion i regret"] },
  { id: "dialog-form", name: "Form dialog", category: "dialogs", description: "A New booking dialog with checked fields that, on save, adds the booking to a list on the page.", tags: ["dialog","modal","form","validation"], useCases: ["new booking","add item","quick create","new task","add contact","new appointment","create event","add expense"], jobs: ["add a new item without leaving the page","book an appointment quickly","create an entry with the right details","fix mistakes before saving"] },
  { id: "drawer-side", name: "Side drawer", category: "dialogs", description: "Choosing a list item slides in a drawer from the right with its details and edits.", tags: ["drawer","side panel","details","edit"], useCases: ["record details","edit panel","order details","contact details","task details","ticket details","quick view","inspector panel"], jobs: ["see the details of an item","edit an item without losing my place","check an order while scanning the list","update a record quickly"] },
  { id: "sheet-bottom", name: "Bottom sheet", category: "dialogs", description: "A phone-style More menu that opens a bottom sheet with Share, Duplicate and Archive.", tags: ["bottom sheet","action sheet","mobile","more menu"], useCases: ["mobile action menu","more options","share menu","item actions","mobile context menu","quick actions"], jobs: ["share an item with someone","duplicate or archive an item","reach more actions on my phone"] },
  { id: "form-account", name: "Create account form", category: "forms", description: "Stacked sign-up form with name, email, a password with show and hide and a strength hint, and a terms checkbox, checked as you go, ending in a confirmation.", tags: ["form","sign up","account","validation","password","registration"], useCases: ["sign up","create account","registration","join page","onboarding signup","member registration","trial signup"], jobs: ["create my account","choose a strong password","join the service","get started with a new account"] },
  { id: "form-settings", name: "Settings form", category: "forms", description: "Two-column settings with profile fields, notification switches and a danger zone whose delete needs typed confirmation, plus a save bar that shows unsaved changes.", tags: ["form","settings","profile","switch","danger zone"], useCases: ["account settings","profile settings","notification preferences","user preferences","delete account","privacy settings","workspace settings"], jobs: ["update my profile details","choose which notifications i get","delete my account safely","save changes to my settings"] },
  { id: "form-wizard", name: "Multi-step form", category: "forms", description: "Three steps (details, preferences, review) with a step indicator, back and next, checks per step, a review with edit links and a final confirmation.", tags: ["form","wizard","steps","multi-step","review"], useCases: ["onboarding flow","checkout steps","booking flow","application form","setup wizard","registration steps","quote request","survey"], jobs: ["complete a long form step by step","review my answers before submitting","set up my account","apply without getting lost"] },
  { id: "form-filters", name: "Search and filter bar", category: "forms", description: "Search, selects and quick filters that narrow a list, with removable chips, Clear all, a live result count and a no-results state.", tags: ["form","search","filter","chips"], useCases: ["search and filter","product filters","listing search","job search","property search","catalog filtering","directory search","advanced search"], jobs: ["narrow down to what i want","search by keyword and category","clear filters and start over","see how many results match"] },
  { id: "bg-soft", name: "Soft gradient", category: "backgrounds", description: "A gentle wash of the accent color at the top, fading into the page.", tags: ["background","gradient","page background","soft"], useCases: ["landing page background","hero background","sign in page background","marketing page","onboarding screen","pricing page background"], jobs: ["feel welcomed by a calm page","focus on the main message","read the page without visual clutter"] },
  { id: "bg-mesh", name: "Mesh gradient", category: "backgrounds", description: "Soft color blooms in the corners from the accent, success and focus colors.", tags: ["background","gradient","page background","mesh"], useCases: ["hero background","landing page background","launch page","creative portfolio","product announcement","event page"], jobs: ["feel the brand's personality","notice a launch or announcement","focus on the main message"] },
  { id: "bg-glow", name: "Top glow", category: "backgrounds", description: "A spotlight of the accent color from the top edge.", tags: ["background","gradient","page background","glow"], useCases: ["hero background","launch page","dark landing page","product announcement","pricing highlight","sign in page background"], jobs: ["focus on the headline","notice what's new","feel the product is modern and polished"] },
  { id: "bg-aurora", name: "Aurora", category: "backgrounds", description: "A slowly turning, blurred blend of the theme colors (still for people who ask for less motion).", tags: ["background","gradient","page background","aurora"], useCases: ["hero background","launch page","ai product landing","creative portfolio","event page","coming soon page"], jobs: ["feel the brand's personality","focus on the main message","notice a launch or announcement"] },
  { id: "bg-split", name: "Diagonal split", category: "backgrounds", description: "Two tones divided on a diagonal.", tags: ["background","gradient","page background","split"], useCases: ["hero background","landing page section","sign in page background","feature highlight","promo section","portfolio header"], jobs: ["see a clear break between sections","focus on the main message","tell the two halves of a page apart"] },
  { id: "bg-ink", name: "Ink band", category: "backgrounds", description: "The accent color as a solid band with a soft highlight; text switches to the on-accent color.", tags: ["background","gradient","page background","ink"], useCases: ["call to action band","stats band","promo section","newsletter section","highlight section","closing section"], jobs: ["notice the key invitation","see a clear break between sections","take the next step"] },
  { id: "bg-dots", name: "Dot grid", category: "backgrounds", description: "A fine grid of dots in the text color.", tags: ["background","pattern","page background","dots"], useCases: ["hero background","developer tool landing","docs page background","feature section","technical product page","portfolio background"], jobs: ["focus on the content on a subtle backdrop","feel the product is precise and technical","read the page without visual clutter"] },
  { id: "bg-grid", name: "Fading grid", category: "backgrounds", description: "Faint grid lines that fade out towards the edges.", tags: ["background","pattern","page background","grid"], useCases: ["hero background","developer tool landing","saas homepage","technical product page","launch page","feature section"], jobs: ["focus on the headline","feel the product is precise and technical","notice a launch or announcement"] },
  { id: "bg-stripes", name: "Diagonal stripes", category: "backgrounds", description: "Thin diagonal stripes in the accent color.", tags: ["background","pattern","page background","stripes"], useCases: ["promo section","sale banner background","highlight section","construction or coming soon page","call to action band"], jobs: ["notice a highlighted section","see a clear break between sections","find out about a sale or offer"] },
  { id: "bg-waves", name: "Waves", category: "backgrounds", description: "Repeating wave lines in the accent color.", tags: ["background","pattern","page background","waves"], useCases: ["hero background","travel site","wellness site","music or audio product","landing page section","event page"], jobs: ["feel calm and at ease","focus on the main message","enjoy a relaxed, flowing page"] },
  { id: "bg-topo", name: "Contour lines", category: "backgrounds", description: "Topographic contour lines in the text color.", tags: ["background","pattern","page background","topo"], useCases: ["outdoor brand site","travel site","maps or location product","adventure booking","hero background","about section"], jobs: ["feel a sense of exploration","focus on the main message","enjoy an outdoorsy, natural feel"] },
  { id: "bg-grain", name: "Film grain", category: "backgrounds", description: "A subtle paper-like grain over the page color.", tags: ["background","pattern","page background","grain"], useCases: ["editorial site","portfolio","studio website","blog background","craft brand site","restaurant site"], jobs: ["enjoy a warm, crafted feel","read comfortably on a textured page","focus on the words and pictures"] },
  { id: "status-badges", name: "Status badges", category: "alerts", description: "Status chips with a colored dot (done, in progress, waiting, failed, draft) and signal lights that pulse while working, on a list whose status moves on.", tags: ["status","badge","chip","signal light","indicator"], useCases: ["order status","task status","deployment status","job queue","ticket status","build progress","workflow tracker","delivery tracking"], jobs: ["see where each item stands","spot what failed at a glance","know when something is still working","track progress over time"] },
  { id: "skeleton-loading", name: "Skeleton loading", category: "alerts", description: "Shimmering placeholders shaped like a card list that swap to the real content after a short delay.", tags: ["skeleton","loading","placeholder","shimmer"], useCases: ["loading state","feed loading","dashboard loading","list loading","search results loading","profile loading"], jobs: ["know content is on its way","wait without the page jumping around","see the page shape before data arrives"] },
  { id: "tabs-underline", name: "Underline tabs", category: "navigation", description: "Accessible tabs with an underline that slides to the active tab, optional counts, and arrow, Home and End keys.", tags: ["tabs","underline","navigation","counts"], useCases: ["section tabs","profile tabs","inbox folders","order status tabs","settings sections","project views","dashboard views"], jobs: ["switch between views quickly","see how many items are in each group","find the right section of a page"] },
  { id: "segmented-control", name: "Segmented control", category: "forms", description: "A segmented choice of three options with a description that changes with the choice, remembered on the device.", tags: ["segmented","radio group","toggle","settings"], useCases: ["view switcher","display preference","theme choice","plan type choice","time range picker","sort mode","delivery option"], jobs: ["pick one option quickly","understand what each choice means","keep my preferred setting next time"] },
  { id: "data-animated-number", name: "Animated numbers", category: "data", description: "Three headline figures that count up when they come into view, with a refresh that loads the next period.", tags: ["stats","count up","kpi","dashboard"], useCases: ["dashboard headline figures","kpi summary","impact numbers","results section","fundraising totals","period report"], jobs: ["see the headline numbers at a glance","check this period's results","refresh figures for the next period"] },
  { id: "chart-radial-gauge", name: "Radial gauges", category: "data", description: "Radial gauges in three sizes that fill with an accent-to-success gradient and animate when values change.", tags: ["gauge","progress","ring","percentage","chart"], useCases: ["goal progress","completion rate","storage usage","fitness goals","budget used","project progress","score display","health metrics"], jobs: ["see how close i am to a goal","check how much is used up","track progress at a glance"] },
  { id: "chart-area", name: "Area chart", category: "data", description: "Two series as smooth areas that draw in, with a legend, a 4 or 12 week switch, a crosshair tooltip and a data table for screen readers.", tags: ["chart","area","trend","time series","report"], useCases: ["trend chart","analytics report","traffic over time","revenue trend","usage over time","sales comparison","time series dashboard"], jobs: ["see how numbers change over time","compare two series side by side","check a value on a specific week","switch between short and long ranges"] },
  { id: "data-diff", name: "Before and after diff", category: "data", description: "A line-by-line comparison with added and removed lines tinted and a unified or side-by-side view.", tags: ["diff","compare","changes","versions"], useCases: ["version comparison","code review","document changes","change history","contract revisions","config changes","content review"], jobs: ["see what changed between versions","review edits before accepting","compare before and after side by side"] },
  { id: "card-project", name: "Project cards", category: "cards", description: "Project cards with a picture banner, a status chip, two small radial gauges, the last update, a View button and a menu to rename or delete.", tags: ["projects","dashboard","gauge","progress","status"], useCases: ["projects dashboard","project overview","client projects","campaign tracker","course progress","workspace list","portfolio projects"], jobs: ["see how each project is progressing","open a project to work on it","rename or delete a project","spot which projects need attention"] },
  { id: "card-approval", name: "Approval queue", category: "cards", description: "Requests waiting for a decision, each with what is asked, why, a risk badge, details and a scope choice, with Approve, Deny and a timed Undo.", tags: ["approval","review","refund","decision","queue"], useCases: ["approval queue","refund requests","expense approvals","access requests","moderation queue","leave requests","change requests","review inbox"], jobs: ["approve or deny pending requests","judge the risk before deciding","undo a decision made by mistake","clear the queue of requests"] },
  { id: "hero-gradient", name: "Gradient hero", category: "hero", description: "A dark hero panel with an announcement pill, a light display heading with one phrase in a gradient, and two actions.", tags: ["hero","dark","gradient","announcement","landing"], useCases: ["landing page hero","product launch","ai product homepage","new feature announcement","dark mode homepage","saas homepage","developer tool landing"], jobs: ["hear about what's new","understand what the product does","get started right away","learn more before committing"] },
  { id: "sidebar-app", name: "App sidebar", category: "navigation", description: "Classic app frame: a sidebar with the product mark, page search, grouped pages with icons and a count badge, a New booking button and the signed-in person's menu. It collapses to icons with tooltips, remembers that choice, and becomes a top bar with a drawer on phones.", tags: ["sidebar","navigation","app shell","dashboard","collapsible","search","account menu","drawer","responsive"], useCases: ["app navigation","dashboard layout","admin panel","booking app","crm","project management app","saas app shell","back office"], jobs: ["move between sections of the app","find a page quickly","create a new item from anywhere","manage my account and sign out"] },
  { id: "sidebar-rail", name: "Icon rail and panel", category: "navigation", description: "A slim rail of section icons with tooltips next to a wider panel that lists the chosen section's pages, like an email or chat app. Choosing a page opens it in the main area, and on phones both become a drawer.", tags: ["sidebar","navigation","icon rail","secondary panel","inbox","app shell","tooltips","drawer","responsive"], useCases: ["email app","chat app","messaging","file browser","workspace navigation","help desk","notes app","app navigation"], jobs: ["switch between sections of the app","open a conversation or folder","find a page within a section","keep my place while browsing"] },
  { id: "sidebar-nested", name: "Nested sidebar with pins", category: "navigation", description: "A two-level sidebar tree (Projects, then each project, then its pages) with expandable groups and turning chevrons, plus a Pinned list at the top where pages can be pinned and unpinned. Open groups and pins are both remembered, and on phones it becomes a drawer.", tags: ["sidebar","navigation","tree","nested","expandable","pinned","favorites","app shell","drawer","responsive"], useCases: ["project navigation","documentation navigation","workspace tree","file tree","knowledge base","wiki","multi-project app"], jobs: ["find a page inside a project","pin pages i use often","keep my open folders between visits","move between projects quickly"] },
  { id: "auth-sign-in", name: "Sign in", category: "auth", description: "Email and password sign-in with show/hide password, remember me, a forgot-password link, inline errors, a signing-in state and plain-text continue-with options.", tags: ["auth","sign in","login","form","password"], useCases: ["sign in","login","member login","account access","customer portal login","admin login","returning user"], jobs: ["sign in to my account","reset a forgotten password","stay signed in on my device","continue with another account"] },
  { id: "auth-sign-up", name: "Sign up", category: "auth", description: "Create-account form with name, email, a password strength meter and live rules checklist, a terms checkbox and a check-your-email success state.", tags: ["auth","sign up","register","form","password strength"], useCases: ["sign up","registration","create account","join form","member registration","onboarding start","account creation","new user signup"], jobs: ["create an account for myself","join the service with my email","set a strong password","get started with a new account"] },
  { id: "auth-split", name: "Sign in, split", category: "auth", description: "Sign-in form beside an accent-gradient picture panel with a member quote that becomes a banner above the form on phones.", tags: ["auth","sign in","login","split","quote"], useCases: ["sign in","login","member login","customer portal login","branded login","account access","returning user login"], jobs: ["sign in to my account","get back to my saved work","access my member area","log in with my email and password"] },
  { id: "auth-forgot-password", name: "Forgot password", category: "auth", description: "Ask for an email to send a reset link, then a check-your-email screen with next steps and a resend button behind a cooldown timer.", tags: ["auth","password reset","forgot password","email","cooldown"], useCases: ["forgot password","password reset","account recovery","reset link request","locked out","recover access"], jobs: ["reset my forgotten password","get back into my account","receive a password reset link","resend the reset email"] },
  { id: "auth-verify-code", name: "Verify code", category: "auth", description: "Six-digit one-time code boxes that auto-advance, fill from a paste and step back on Backspace, with wrong-code errors, an attempt limit and resend.", tags: ["auth","otp","verification","two-step","code input"], useCases: ["email verification","phone verification","two-factor authentication","one-time code","otp entry","login verification","confirm sign up","magic code login"], jobs: ["confirm my email address","verify my phone number","prove it is really me","finish signing in securely","get a new code sent"] },
  { id: "page-server-error", name: "Server error (500)", category: "alerts", description: "A 500 page with a server illustration, a retry button with a progress state, a copyable reference code and a support link.", tags: ["error","500","server error","retry","page"], useCases: ["server error","500 page","error page","something went wrong","error boundary","service failure","crash screen"], jobs: ["try again after something broke","report a problem to support","understand what went wrong","get back to what i was doing"] },
  { id: "page-maintenance", name: "Planned maintenance", category: "alerts", description: "Planned maintenance page with start time, expected return time and countdown, a filterable service status list and a notify-me form.", tags: ["maintenance","downtime","status","page","notify"], useCases: ["maintenance page","planned downtime","scheduled outage","service status","system upgrade notice","outage notice","back soon"], jobs: ["know when the service is back","see which features are affected","get notified when it returns","plan around the downtime"] },
  { id: "page-offline", name: "Offline", category: "alerts", description: "You're-offline page that lists what still works and what waits, shows changes saved on the device, and retries or detects when the connection returns.", tags: ["offline","connection","retry","error","page"], useCases: ["offline mode","no connection","offline screen","connection lost","offline-first app","sync pending","network error"], jobs: ["keep working without internet","know my changes are saved","reconnect when the network returns","see what still works offline"] },
  { id: "breadcrumbs", name: "Breadcrumbs", category: "wayfinding", description: "Breadcrumb trail with a home icon whose middle levels fold into a \"…\" button on phones, with aria-current on the last crumb; clicking a crumb moves you up to that level.", tags: ["breadcrumbs","navigation","trail","hierarchy","responsive"], useCases: ["breadcrumb navigation","category hierarchy","folder path","docs navigation","product category trail","nested settings","file browser path"], jobs: ["see where i am in the site","go back up a level","find my way through nested pages"] },
  { id: "pagination", name: "Pagination", category: "wayfinding", description: "Numbered pagination with previous/next, ellipses for long ranges, a page-size select, a status filter and a \"Showing 21–40 of 312\" line over a list of bookings.", tags: ["pagination","pages","page size","list","navigation"], useCases: ["paged list","search results","order history","bookings list","transaction list","data table paging","records list","archive"], jobs: ["browse through a long list","jump to a specific page","show more results per page","filter records by status"] },
  { id: "tabs-pills", name: "Pill tabs", category: "wayfinding", description: "Rounded pill tabs with live counts and one tab panel, using arrow keys, Home and End with roving tabindex, where each order can be moved on to the next stage.", tags: ["tabs","pills","counts","tablist","keyboard"], useCases: ["order queue","status tabs","order fulfilment","pipeline stages","ticket queue","task stages","filtered list views","kitchen orders"], jobs: ["sort work into stages","move an order to the next stage","see how many items are waiting","focus on one group at a time"] },
  { id: "dropdown-menu", name: "Actions menu", category: "wayfinding", description: "A \"more\" button on each row that opens a keyboard-operable menu with icons, a separator and a destructive Delete, plus inline rename, duplicate, copy link and undo.", tags: ["dropdown","menu","actions","kebab","keyboard"], useCases: ["row actions","file list actions","document list","item management","context menu","project list","record actions"], jobs: ["rename or duplicate an item","delete something i no longer need","share a link to an item","undo a mistake quickly"] },
  { id: "steps-progress", name: "Steps progress", category: "wayfinding", description: "Step indicator marking steps done, current or upcoming, horizontal on wide screens and vertical on phones, with Back/Next buttons and a finished state.", tags: ["steps","progress","stepper","wizard","booking"], useCases: ["checkout steps","booking flow","onboarding wizard","multi-step form","application process","setup wizard","order progress","registration steps"], jobs: ["see how far along i am","move through a booking step by step","go back and change an earlier step","finish a long form in parts"] },
  { id: "tooltips", name: "Tooltips", category: "wayfinding", description: "A week toolbar whose icon buttons show tooltips on hover and focus on all four sides, linked with aria-describedby and closed with Escape.", tags: ["tooltip","hint","toolbar","icon buttons","accessibility"], useCases: ["toolbar hints","icon buttons","calendar toolbar","editor toolbar","field help","control explanations","accessibility hints"], jobs: ["understand what an icon does","learn the controls without guessing","get a quick hint without leaving"] },
  { id: "avatar-group", name: "Avatar group", category: "cards", description: "Initial avatars on theme colors in four sizes with status dots, a stacked group ending in \"+5\" that expands, and a filterable list of people.", tags: ["avatars","team","presence","status","people"], useCases: ["team members","collaborators","attendee list","online presence","shared with","project members","participants","assignees"], jobs: ["see who is on the team","check who is online now","see everyone attending","find a specific person"] },
  { id: "cookie-consent", name: "Cookie consent", category: "alerts", description: "Cookie banner with equally weighted Accept all and Reject non-essential plus Manage, a dialog with category switches (essential locked on), the choice remembered in localStorage and a Cookie settings button to reopen it.", tags: ["cookies","consent","privacy","banner","dialog"], useCases: ["cookie banner","privacy consent","gdpr consent","cookie preferences","tracking consent","privacy settings"], jobs: ["decide which cookies to allow","reject non-essential tracking","change my cookie choice later","protect my privacy"] },
  { id: "landing-lead", name: "Lead generation landing", category: "landings", description: "Free-guide lead page with the promise and a short validated form above the fold, a chapter list beside a drawn book cover, the author's bio, three reader quotes and a closing link back to the form.", tags: ["landing","lead generation","form","guide","consultation","studio","page template"], useCases: ["lead magnet","free guide download","ebook landing","consultation booking","lead capture","checklist download","newsletter opt-in","webinar signup"], jobs: ["get the free guide","learn what the guide covers","decide if the author is credible","book a free consultation"] },
  { id: "landing-sales", name: "Long-form sales page", category: "landings", description: "Reading-width sales page for one course: the problem, a before-and-after comparison, a week-by-week curriculum accordion, a price card where you choose to pay once or in 3 payments and enrol, a guarantee seal, an FAQ and a closing call to action.", tags: ["landing","sales page","course","pricing","guarantee","faq","accordion","page template"], useCases: ["sales page","online course","coaching program","workshop sales","digital product","course enrolment","membership offer","ebook sales"], jobs: ["decide if the course is right for me","see what i will learn each week","choose how to pay","enrol in the course","get my questions answered before buying"] },
  { id: "landing-prelaunch", name: "Pre-launch waitlist", category: "landings", description: "Full-screen pre-launch page with a live countdown, a waitlist email form that shows your place in line and a referral link you can copy, and a row of features coming on launch day.", tags: ["landing","pre-launch","waitlist","countdown","coming soon","referral","page template"], useCases: ["waitlist","pre-launch","coming soon","early access","beta signup","launch countdown","referral waitlist"], jobs: ["join the waitlist early","know when it launches","move up the waitlist by sharing","see what is coming on launch day"] },
  { id: "landing-product", name: "Single product page", category: "landings", description: "Product page for a desk lamp: a gallery with switchable drawn views, a buy box with rating, finish swatches, shade options, a quantity stepper and add-to-bag, tabs for details, specs and shipping, and a reviews summary you can filter by star rating.", tags: ["landing","product","ecommerce","gallery","options","reviews","tabs","page template"], useCases: ["product detail","product page","single product store","direct-to-consumer product","hero product","product reviews","item detail"], jobs: ["see the product from every angle","choose the right option for me","add the product to my bag","read what other buyers think","check shipping and specs"] },
  { id: "landing-subscription", name: "Subscription offer", category: "landings", description: "Coffee subscription page with a split hero and how-it-works steps, plus a box builder (size, roast, grind and a delivery-frequency toggle) next to a live order summary and a validated sign-up.", tags: ["landing","subscription","plan picker","order summary","meal kit","coffee","page template"], useCases: ["subscription box","meal kit","coffee subscription","plan builder","recurring delivery","pet food subscription","flower delivery","subscribe and save"], jobs: ["build a subscription that fits me","choose how often it arrives","see what it will cost","start my subscription"] },
  { id: "landing-click-through", name: "Click-through page", category: "landings", description: "Warm-up page for one sign-up: a centered promise with social proof, a row of customer names, three benefits, a time-saved slider, a quote carousel and a closing email sign-up.", tags: ["landing","click-through","saas","trial","social proof","calculator","carousel","page template"], useCases: ["free trial signup","saas landing","app download","ad campaign landing","roi calculator","product signup","free account offer"], jobs: ["decide whether to try the product","see how much time i would save","see who already uses it","start a free trial"] },
  { id: "home-saas", name: "SaaS homepage", category: "homepages", description: "A whole homepage for scheduling software for small studios, with a centered hero over a calendar preview drawn in CSS, integrations, a bento grid of features, a tabbed how-it-works, pricing with a monthly/yearly switch, FAQ, a trial sign-up and a column footer.", tags: ["page","homepage","saas","landing","pricing","tabs","faq","signup","b2b"], useCases: ["saas homepage","software product site","b2b marketing site","booking software","scheduling tool","pricing plans","free trial","product marketing"], jobs: ["understand what the software does","compare plans for my budget","see how it fits my tools","start a free trial"] },
  { id: "home-startup", name: "Startup homepage", category: "homepages", description: "A whole homepage for an early-stage startup building a shared household planner, with a bold left-aligned hero and a working chore board, the mission, the product, traction stats and a milestone timeline, the founders, open roles filtered by team, and a future-roles form.", tags: ["page","homepage","startup","mission","traction","timeline","team","careers","hiring"], useCases: ["startup homepage","company website","careers","open roles","about the team","mission statement","traction milestones","investor-facing site"], jobs: ["understand what the company is building","learn who the founders are","find a job that fits me","hear about future roles"] },
  { id: "home-mobile-app", name: "Mobile app homepage", category: "homepages", description: "A whole homepage for a budgeting app, with phone mockups drawn in CSS and SVG, download buttons and a rating, four setup steps, a feature tour that changes the phone screen, stats, reviews, FAQ and a text-me-the-link form.", tags: ["page","homepage","mobile app","phone mockup","download","features","reviews","faq","budgeting"], useCases: ["mobile app landing","app download page","app marketing site","budgeting app","feature tour","app store promotion","app reviews"], jobs: ["decide whether to download the app","see how the app works","get the download link on my phone","read what users think"] },
  { id: "home-personal", name: "Personal homepage", category: "homepages", description: "A one-person homepage for a freelance product designer and developer, with a typographic intro and availability, filterable selected work with drawn covers, services and skills, an experience timeline, a client quote, recent writing and a project enquiry form.", tags: ["page","homepage","personal","portfolio","freelancer","resume","blog","contact"], useCases: ["personal website","portfolio","freelancer site","designer portfolio","developer portfolio","online resume","personal blog","hire me"], jobs: ["see the freelancer's best work","check if they are available","learn what services they offer","send a project enquiry"] },
  { id: "site-cafe", name: "Cafe website", category: "sites", description: "One-page cafe or restaurant site with a centered header, warm hero, highlights, a tabbed menu with a vegetarian filter, opening hours with today marked, a location card, a table-booking form and a footer (layout from HTML5 UP Arcana, credited).", tags: ["page","template","cafe","restaurant","menu","tabs","hours","reservations","booking","form","html5up"], useCases: ["cafe website","restaurant website","menu","opening hours","table booking","bistro","bar website","bakery"], jobs: ["see what is on the menu","check if they are open today","find how to get there","book a table"] },
  { id: "site-agency", name: "Creative agency website", category: "sites", description: "One-page studio site with a side-panel menu, bold banner, filterable work tiles in alternating widths, services, a four-step process, client names with a quote, and a project enquiry form beside the contact details (layout from HTML5 UP Forty, credited).", tags: ["page","template","agency","studio","portfolio","work","services","process","clients","contact","html5up"], useCases: ["agency website","design studio","creative portfolio","services overview","case studies","client work","consultancy site","project enquiry"], jobs: ["see the studio's past work","understand how they work","find out what services they offer","start a project with the studio"] },
  { id: "site-photographer", name: "Photographer portfolio", category: "sites", description: "One-page photographer site with a full-height intro, alternating statement panels, a large gallery with a category filter and a keyboard lightbox dialog, three packages, and a date-check booking form (layout from HTML5 UP Big Picture, credited).", tags: ["page","template","photographer","portfolio","gallery","filter","lightbox","packages","booking","html5up"], useCases: ["photographer portfolio","photo gallery","wedding photography","portrait studio","artist portfolio","image gallery","photography packages","session booking"], jobs: ["browse the photographer's work","compare photography packages","check if my date is free","book a photo session"] },
  { id: "site-magazine", name: "Online magazine", category: "sites", description: "Magazine or blog front page with a sidebar for search, sections, most read and saved stories (it folds into a drawer on phones), a featured story, section tiles that filter the feed, a latest-articles grid with save and load more, and a newsletter sign-up (layout from HTML5 UP Editorial, credited).", tags: ["page","template","magazine","blog","editorial","articles","search","categories","newsletter","html5up"], useCases: ["online magazine","blog","news site","editorial","article feed","newsletter","content hub","publication front page"], jobs: ["find something good to read","browse stories by section","save articles for later","subscribe to the newsletter"] },
  { id: "site-real-estate", name: "Real-estate agency website", category: "sites", description: "One-page estate agent site with a hero property search (buy or rent, area, bedrooms, max price), proof stats, sortable listing cards with save, agent profiles and a free valuation form (layout from HTML5 UP Dopetrope, credited).", tags: ["page","template","real estate","property","listings","search","filters","agents","valuation","form","html5up"], useCases: ["real estate listings","property search","rental listings","estate agent","letting agency","home valuation","property portal","agent profiles"], jobs: ["find a home in my budget","search homes to buy or rent","save homes i like","get my home valued","find a local agent"] },
  { id: "site-fitness", name: "Fitness studio site", category: "sites", description: "One-page yoga and fitness studio site with a centered masthead, a class timetable you can filter by day, what's included, the trainers, membership prices with a monthly/annual switch and a free-trial form; layout adapted from HTML5 UP Escape Velocity.", tags: ["page","fitness","yoga","gym","studio","timetable","schedule","filter","pricing","trainers","free trial","form","html5up"], useCases: ["gym website","yoga studio","class timetable","fitness classes","pilates studio","membership pricing","free trial class","trainer profiles"], jobs: ["find a class that fits my schedule","choose a membership","meet the trainers","book a free trial"] },
  { id: "site-nonprofit", name: "Charity site", category: "sites", description: "One-page charity site with a tall banner, a mission box with impact figures over it, four programs, a community quote, a donation picker (one-off or monthly, preset or own amount, gift aid) that confirms the gift without taking payment, and a volunteer sign-up; layout adapted from HTML5 UP Alpha.", tags: ["page","nonprofit","charity","donate","donation","impact","programs","volunteer","sign-up","form","html5up"], useCases: ["charity website","nonprofit","donation page","fundraising","volunteer signup","foundation site","community group","impact report"], jobs: ["donate to a cause i care about","see the impact of my gift","set up a monthly donation","sign up to volunteer"] },
  { id: "site-event", name: "Conference site", category: "sites", description: "One-page conference site with a full-height hero showing date and venue, headline numbers, a schedule in day tabs with sessions you can save to My agenda, keynote spotlights and the line-up, ticket types with a quantity picker that holds a reservation, and travel and access info; layout adapted from HTML5 UP Fractal.", tags: ["page","event","conference","summit","schedule","agenda","tabs","speakers","tickets","travel","faq","html5up"], useCases: ["conference website","event schedule","agenda","speaker lineup","event tickets","summit","festival","meetup"], jobs: ["plan which sessions to attend","see who is speaking","buy tickets for the event","find out how to get there"] },
  { id: "site-clinic", name: "Health clinic site", category: "sites", description: "One-page clinic site with a centered emblem header and a live open-now line, services in alternating feature boxes, the practitioners, opening hours with today highlighted, an appointment request form, and insurers, self-pay fees and FAQs; layout adapted from HTML5 UP Directive.", tags: ["page","clinic","health","medical","practice","physiotherapy","services","practitioners","opening hours","appointment","insurance","faq","form","html5up"], useCases: ["clinic website","medical practice","dental practice","physiotherapy","appointment request","practitioner profiles","opening hours","healthcare services"], jobs: ["book an appointment","check if the clinic is open now","find the right practitioner","see if my insurance is accepted"] },
  { id: "site-coming-soon", name: "Coming-soon page", category: "sites", description: "Full-screen coming-soon page for a new local business with a short promise, a live countdown to opening day, a notify-me form that spots repeat sign-ups, fit-out milestones and plain-text social links; layout adapted from HTML5 UP Eventually.", tags: ["page","coming soon","launch","pre-launch","countdown","notify","waitlist","email","local business","bakery","html5up"], useCases: ["coming soon","opening soon","new business launch","pre-opening","notify me","launch countdown","local business teaser","under construction"], jobs: ["know when it opens","get notified on opening day","follow the opening progress"] },
  { id: "nb-buttons", name: "Neobrutal buttons", category: "neobrutal", description: "Chunky ink-bordered buttons in primary, secondary, danger, icon, disabled and loading forms, with a hard shadow that lifts on hover and presses flat on click.", tags: ["buttons","neobrutalism","loading","icon button","toggle","bold"], useCases: ["button styles","playful ui","bold design system","action buttons","loading buttons","icon buttons","ui kit"], jobs: ["take an action with one click","see that my action is working","toggle an option on or off"] },
  { id: "nb-cards", name: "Neobrutal cards", category: "neobrutal", description: "A feature card, a pricing card with a tilted sticker badge and a profile card with stats and a follow toggle, all in thick borders and hard shadows.", tags: ["cards","pricing","profile","feature","sticker","neobrutalism"], useCases: ["pricing card","profile card","feature card","plan picker","team member card","creator profile","bold product page"], jobs: ["choose a plan","follow a person i like","learn about a key feature"] },
  { id: "nb-form", name: "Neobrutal sign-up form", category: "neobrutal", description: "A bold sign-up form with inputs, a select, a pill radio group, a textarea with a counter and a terms checkbox, showing inline errors and a success panel.", tags: ["form","sign up","validation","radio","checkbox","select","neobrutalism"], useCases: ["sign up form","club membership","waitlist form","class registration","event registration","application form","contact form"], jobs: ["join a club or studio","register for a class","sign up for the waitlist","tell them about myself"] },
  { id: "nb-feedback", name: "Neobrutal feedback", category: "neobrutal", description: "Dismissable alerts in info, success, warning and error tones, status badges, and chunky progress bars including a running upload.", tags: ["alerts","badges","progress","notifications","status","neobrutalism"], useCases: ["alerts","notifications","status badges","upload progress","system messages","booking status","dashboard notices"], jobs: ["know if something worked","see the status of my booking","track an upload until it finishes","dismiss notices i have read"] },
  { id: "nb-tabs-accordion", name: "Neobrutal tabs and accordion", category: "neobrutal", description: "Folder-style tabs driven by arrow keys, Home and End, plus a chunky FAQ accordion with open-all and close-all.", tags: ["tabs","accordion","faq","keyboard","disclosure","neobrutalism"], useCases: ["faq","class details","plan comparison","product details","help section","tabbed content","policies"], jobs: ["find answers to my questions","compare details between options","read only the part i need"] },
  { id: "nb-landing", name: "Neobrutal landing", category: "neobrutal", description: "A loud landing hero with a bookable slot preview and sticker, a three-card feature row and a call to action with an email sign-up.", tags: ["landing","hero","features","call to action","email signup","neobrutalism"], useCases: ["landing page","playful product homepage","studio homepage","event homepage","waitlist signup","booking service landing","product launch"], jobs: ["understand what the product offers","see an available booking slot","join the waitlist with my email"] },
  { id: "input-file-upload", name: "File upload", category: "forms", description: "Drag-and-drop zone with a browse button, a file list with type icons, sizes, simulated upload progress and remove, refusing files that aren't images or PDFs or are over 10 MB.", tags: ["upload","file","drag and drop","dropzone","attachment","progress","validation"], useCases: ["file upload","photo upload","document upload","receipt upload","attachments","id verification upload","resume upload","image upload"], jobs: ["attach photos to my request","upload receipts or documents","remove a file i added by mistake","see my upload finish"] },
  { id: "input-range", name: "Range sliders", category: "forms", description: "A single slider with a live value and a two-thumb price range kept in order, with min and max number fields that stay in sync and filter a results list.", tags: ["range","slider","price range","dual thumb","filter","min max"], useCases: ["price filter","budget filter","distance filter","search filters","price range","duration filter","rental search"], jobs: ["narrow results to my budget","find options within my distance","set a minimum and maximum"] },
  { id: "input-quantity", name: "Quantity stepper", category: "forms", description: "Minus and plus quantity steppers in three sizes with min and max limits, typed entry clamped on blur, a disabled sold-out row and a live basket total.", tags: ["quantity","stepper","number input","counter","tickets","cart"], useCases: ["ticket quantity","cart quantity","guest count","order quantity","portion selector","stock adjustment","basket"], jobs: ["choose how many tickets i need","change the number of items","see the running total","set the number of guests"] },
  { id: "input-button-group", name: "Button groups", category: "forms", description: "Editor toolbar with a single-choice alignment group, multi-toggle bold, italic and underline buttons, and a split save button with a keyboard-navigable menu.", tags: ["button group","toolbar","toggle","aria-pressed","split button","menu","formatting"], useCases: ["editor toolbar","text formatting","note editor","view switcher","save options","rich text editor","document editor"], jobs: ["format my text","align my content","save my work in different ways","switch between views"] },
  { id: "input-radio-cards", name: "Radio cards", category: "forms", description: "Plan and delivery choices shown as radio cards with descriptions, prices, badges and an unavailable option, built on native radios in fieldsets.", tags: ["radio","radio cards","plan picker","delivery options","fieldset","choice"], useCases: ["plan selection","delivery options","shipping method","subscription tier","checkout options","membership choice","service package"], jobs: ["pick the plan that suits me","choose how my order is delivered","compare options with prices","confirm my choice"] },
  { id: "input-textarea", name: "Textareas", category: "forms", description: "An auto-growing textarea with a character counter and limit warning, plus a comment box with a formatting toolbar, Cancel and Post that adds to a saved comment list.", tags: ["textarea","character count","auto grow","comment box","comments","limit"], useCases: ["comments","reviews","feedback form","booking notes","message box","discussion thread","notes field","support message"], jobs: ["leave a comment","write a review","add notes to my booking","send feedback within the limit"] },
  { id: "input-select", name: "Selects", category: "forms", description: "A custom listbox select with type-ahead, arrow keys and Escape, a native select styled to match, and a searchable select that filters as you type.", tags: ["select","dropdown","listbox","combobox","searchable select","type-ahead","native select"], useCases: ["country picker","category select","searchable dropdown","form selects","timezone picker","assignee picker","settings options"], jobs: ["pick an option from a long list","find my option by typing","choose a category for my item"] },
  { id: "timeline-activity", name: "Activity timeline", category: "data", description: "Vertical activity feed grouped by day, with an icon per event kind, relative times, a kind filter and a Show older button that loads earlier days.", tags: ["timeline","activity","feed","history","log","events","load more"], useCases: ["activity feed","audit log","order history","customer history","change log","recent activity","event log","notifications history"], jobs: ["see what happened recently","trace the history of an order","filter events by type","look back at older activity"] },
  { id: "details-list", name: "Details list", category: "cards", description: "A booking record shown as label and value rows, each editable in place with Save, Cancel and checks before saving, plus a copy button for the reference.", tags: ["description list","details","record","inline edit","copy","booking","order"], useCases: ["booking details","order details","account details","profile details","record view","reservation summary","customer record"], jobs: ["check the details of my booking","fix one wrong detail","copy my reference number","update my contact information"] },
  { id: "stats-compare", name: "Stats compared", category: "data", description: "Stat tiles with a week, month or quarter switch, up or down change against the previous period, and a small SVG trend line.", tags: ["stats","kpi","comparison","sparkline","trend","period","dashboard"], useCases: ["kpi dashboard","metrics overview","sales summary","performance report","business stats","weekly report","admin dashboard"], jobs: ["see how the business is doing","compare this period to the last","spot trends at a glance","track key numbers over time"] },
  { id: "progress-set", name: "Progress set", category: "data", description: "Four progress styles: a labelled upload bar, a segmented multi-step order bar, a stacked storage-by-type bar with legend, and a goal ring.", tags: ["progress","progress bar","steps","usage","storage","ring","circular","goal"], useCases: ["upload progress","order status","storage usage","goal tracking","quota usage","fundraising goal","delivery tracking","fitness goal"], jobs: ["track my order's progress","see how much storage i have left","check progress toward my goal","follow an upload until it finishes"] },
  { id: "announcement-bar", name: "Announcements", category: "alerts", description: "Three announcement styles: a top bar with a link and a close button that stays closed, a pill above a heading, and a notice that floats at the bottom of the screen.", tags: ["announcement","banner","pill","notice","dismiss","news"], useCases: ["announcement banner","promo bar","product update","launch news","sale announcement","site notice","whats new"], jobs: ["hear about what is new","learn about a current offer","dismiss news i have seen"] },
  { id: "logo-cloud", name: "Logo cloud", category: "testimonials", description: "\"Trusted by\" wordmarks of invented businesses as a row, a grid and a scrolling strip that pauses on hover, on focus or with a button, and stays still under reduced motion.", tags: ["logos","trusted by","social proof","marquee","customers","clients"], useCases: ["trusted by","customer logos","client list","partners","social proof","as featured in","sponsors"], jobs: ["see who already uses this","judge if the company is credible","check if businesses like mine use it"] },
  { id: "poll-vote", name: "Poll", category: "forms", description: "A poll card: pick one answer and vote, then see animated result bars with percentages, the total vote count and your own answer marked, with a button to change your vote.", tags: ["poll","vote","survey","results","radio","feedback"], useCases: ["poll","community vote","survey question","feature voting","member feedback","quick survey","event voting"], jobs: ["vote on what happens next","see what others think","change my vote","share my opinion quickly"] },
  { id: "accordion-variants", name: "Accordion styles", category: "faq", description: "Accordions in bordered, separate-card and with-icon styles, with a one-at-a-time or open-several switch, built from buttons with aria-expanded and arrow-key movement.", tags: ["accordion","faq","collapse","expand","disclosure","questions"], useCases: ["faq","help center","policies","product details","terms summary","knowledge base","support questions"], jobs: ["find answers to my questions","read only the part i need","scan policies quickly"] },
  { id: "shop-cart-drawer", name: "Cart drawer", category: "commerce", description: "A Bag (3) button that opens a slide-over cart with quantity steppers, remove with undo, a free-delivery progress bar, the subtotal and a checkout that shows an order confirmation without taking payment.", tags: ["cart","bag","drawer","slide-over","checkout","quantity","undo","free delivery","shop"], useCases: ["shopping cart","mini cart","slide-out cart","online store","basket","checkout","order review"], jobs: ["check what is in my bag","change quantities before buying","reach free delivery","check out quickly"] },
  { id: "shop-cart-page", name: "Cart page", category: "commerce", description: "A full cart page with an items table, quantity steppers, remove with undo, a promo code that accepts one code (with an inline error otherwise), delivery options and an order summary.", tags: ["cart","basket","promo code","delivery","order summary","table","checkout","shop"], useCases: ["cart page","shopping basket","checkout review","order summary","promo code","delivery options","online store"], jobs: ["review my order before paying","apply a discount code","choose a delivery option","remove items i do not want"] },
  { id: "shop-product-cards", name: "Product cards", category: "commerce", description: "Three product card styles in a row: image-top with a wishlist heart, horizontal with a star rating and sale price, and minimal with color swatches, each with an add-to-bag button that shows its states.", tags: ["product card","wishlist","rating","swatches","add to bag","sale","shop"], useCases: ["product grid","product listing","featured products","related products","wishlist","shop catalog","sale items"], jobs: ["browse products","save items to my wishlist","add a product to my bag","pick the color i want"] },
  { id: "shop-collection", name: "Collection with filters", category: "commerce", description: "A product collection page with a filter sidebar (price range, size, color, in stock) that becomes a drawer on phones, a sort menu, a live result count, removable filter chips and a no-match state.", tags: ["collection","category page","filters","sort","chips","product grid","drawer","shop"], useCases: ["product catalog","category page","search results","filtered listing","shop by category","online store","product browsing"], jobs: ["find products that fit my size","filter products by price","sort products by what matters to me","narrow down a big range"] },
  { id: "shop-quick-view", name: "Quick view", category: "commerce", description: "A product grid where Quick view opens a dialog with a three-view gallery placeholder, color and size options, a quantity stepper and add to bag.", tags: ["quick view","product dialog","modal","gallery","size","color","add to bag","shop"], useCases: ["quick view","product grid","product preview","shop catalog","fast add to cart","category browsing"], jobs: ["check a product without leaving the page","pick a size and color","add a product to my bag quickly"] },
  { id: "app-analytics", name: "Analytics dashboard", category: "apptemplates", description: "A whole analytics screen with its own top bar and date range, KPI tiles with change, an SVG line chart with hover and keyboard tooltip, a sortable top pages table and a traffic sources bar list.", tags: ["app","dashboard","analytics","chart","kpi","table","sortable","date range"], useCases: ["analytics dashboard","website analytics","traffic report","kpi dashboard","reporting","metrics overview","marketing dashboard","admin home"], jobs: ["see how my site is performing","compare traffic across date ranges","find my top pages","see where visitors come from"] },
  { id: "app-storefront", name: "Shop home screen", category: "apptemplates", description: "A shop's home screen with a header search and bag count (the bag opens as an editable panel), category tabs, a dismissible promo banner, a product grid with add-to-bag and a footer.", tags: ["app","shop","ecommerce","storefront","product grid","cart","search","tabs"], useCases: ["shop home","online store","storefront","product catalog","marketplace home","booking shop","ecommerce app"], jobs: ["browse products by category","search for a product","add items to my bag","find current deals"] },
  { id: "app-support-inbox", name: "Support inbox", category: "apptemplates", description: "A three-pane support inbox: conversations with Open/Pending/Closed filters, search and unread dots, the selected thread with status buttons and a reply box with canned replies, and the customer's details, folding to one column on phones.", tags: ["app","inbox","support","help desk","messages","chat","filters"], useCases: ["support inbox","help desk","customer messages","ticketing","shared inbox","customer service","live chat inbox","conversations"], jobs: ["answer customer questions quickly","find a customer conversation","track which tickets are open","reply with a saved answer"] },
  { id: "app-settings", name: "Account settings", category: "apptemplates", description: "An account settings screen whose section nav (Profile, Notifications, Billing, Team) switches panels, with validated forms that show unsaved, saving and saved states, team invites and a danger zone that needs the name typed to confirm.", tags: ["app","settings","account","profile","billing","team","notifications","danger zone"], useCases: ["account settings","profile settings","notification preferences","billing","team management","workspace settings","user preferences","subscription management"], jobs: ["update my profile details","control which notifications i get","change my plan","invite my team","delete my workspace safely"] },
  { id: "app-kanban", name: "Task board", category: "apptemplates", description: "A kanban task board whose cards move with arrow buttons, Alt+arrow keys or drag, with inline add card, a work-in-progress limit warning, an assignee filter and cards remembered in this browser.", tags: ["app","kanban","board","tasks","drag and drop","project","workflow"], useCases: ["kanban board","task board","project management","sprint board","sales pipeline","content calendar","workflow board","to-do board"], jobs: ["track tasks through stages","move work forward","see what each person is working on","keep work in progress under control"] },
  { id: "site-docs", name: "Docs site", category: "sites", description: "Documentation site for a small scheduling API with a version picker, live page search, collapsible section nav (drawer on phones), an article with callouts, npm/pnpm/yarn install tabs, copyable code blocks and a parameters table, a scroll-following \"On this page\" list, previous/next links and a \"Was this page helpful?\" prompt.", tags: ["docs","documentation","developer","api","sidebar","search","code","table of contents","tabs","feedback"], useCases: ["documentation","api docs","developer docs","help center","knowledge base","user guide","sdk reference","getting started guide"], jobs: ["learn how to use the api","find the right docs page","copy install and code examples","check parameters for a call"] },
  { id: "home-devtool", name: "Developer tool homepage", category: "homepages", description: "Homepage for an open-source local-first sync library with a copyable install command, a CSS terminal that types out a session, framework tabs for the code sample, a features grid, an SVG \"how it works\" diagram, switchable benchmark bars, open-source stats, free/team pricing with a seat counter, FAQ and a docs-link footer.", tags: ["developer","devtool","cli","sdk","open source","terminal","code","benchmarks","pricing","faq","landing"], useCases: ["developer tool homepage","open source project","sdk landing","cli tool","library homepage","api product","developer pricing","devtool marketing"], jobs: ["install the library quickly","see how it works with my framework","compare performance with alternatives","choose a plan for my team"] },
  { id: "app-ai-chat", name: "AI assistant chat", category: "apptemplates", description: "An AI assistant app screen with chat history (new, search, rename, delete with undo), a thread whose replies stream in word by word with Stop, light formatting with copyable code blocks, suggested prompts, and a composer with attach chip, model picker and character limit; the assistant is simulated in the browser from canned replies.", tags: ["app","ai","chat","assistant","streaming","composer","history","sidebar","drawer","markdown"], useCases: ["ai chat","chatbot","ai assistant","conversation history","customer support bot","writing assistant","coding assistant","q&a assistant"], jobs: ["ask the assistant a question","pick up a past conversation","copy code from an answer","get started with a suggested prompt"] },
  { id: "app-admin", name: "Admin panel: users and roles", category: "apptemplates", description: "An admin panel screen with a colored sidebar, a top bar with search and the signed-in admin, a users table with search, role and status filters, sorting, selection with bulk role change and confirmed deactivation, pagination, a user detail drawer with an activity log, an invite dialog, and a roles and permissions matrix that saves.", tags: ["app","admin","users","table","filters","bulk-actions","drawer","dialog","permissions","roles"], useCases: ["admin panel","user management","roles and permissions","access control","team directory","member management","back office","user list"], jobs: ["manage who has access","change people's roles in bulk","invite a new user","deactivate a user safely","review a user's activity"] },
];

/**
 * New pieces waiting for the owner's approval: shown on the Component library page under "Waiting for your approval",
 * left out of the library list, the agents' picks and the kept index until approved (then moved into LIBRARY_SECTIONS).
 */
export const PROPOSED_SECTIONS: LibrarySection[] = [
];

/** The sections whose tags appear in some text (a request or a screen's spec), best matches first. */
export function sectionsFor(text: string, max = 6): LibrarySection[] {
  const t = text.toLowerCase();
  return LIBRARY_SECTIONS.map((s) => ({ s, n: s.tags.filter((tag) => t.includes(tag)).length }))
    .filter((x) => x.n > 0)
    .sort((a, b) => b.n - a.n)
    .slice(0, max)
    .map((x) => x.s);
}
