/**
 * Component recipes, distilled from the CSSVibes prompt library: how to build common components (alerts, tooltips,
 * toasts, badges, cards, pricing, sign-in, galleries, status tracking, landing sections) from FlowCode's building
 * blocks and design tokens. Each is a skill the agents pick up when a task mentions that component, so the result is
 * consistent with the rest of the app instead of a one-off design.
 */
import type { SkillSpec } from "@flowcode/contracts";

const INSPECT =
  "src/styles/tokens.css (colours, type, space, radius, surface and control tokens), src/components/ui (index.tsx and screen-parts.tsx), the screens in src/screens/ and the spec in spec/.";
const A11Y =
  "Keyboard reachable in a sensible order with a visible focus ring; every control and icon-only button labelled; status changes announced (role=status, or role=alert for errors); never colour alone (add an icon or words); targets at least 44px; works at 375px with no sideways scrolling; prefers-reduced-motion respected.";
const REPORT = "Report in plain language: What changed · What the user can do now · What I checked (only what you actually verified) · Notes (assumptions, limits).";

function recipe(r: { id: string; purpose: string; triggers: string[]; use: string; notUse: string; steps: string[]; edge: string; done: string[]; qa: string }): SkillSpec {
  return {
    id: r.id,
    version: "1.0.0",
    roles: ["coder", "critic"],
    triggers: r.triggers,
    enabled: true,
    source: "builtin",
    purpose: r.purpose,
    instructions: [
      `When to use: ${r.use}`,
      `When not to use: ${r.notUse}`,
      `Inspect first: ${INSPECT}`,
      `Process:\n${r.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}`,
      `Accessibility and responsive: ${A11Y}`,
      `Edge cases: ${r.edge}`,
      `Done when: ${r.done.join("; ")}.`,
      `QA: ${r.qa}`,
      REPORT,
    ].join("\n"),
    allowedTools: ["list_files", "read_file", "search_code", "apply_patch", "create_file", "run_script", "task_complete", "report_blocked"],
    inputSchema: "Task",
    outputSchema: "ChangedPaths",
    policies: { network: "denied", filesystem: "governed_write" },
    acceptance: r.done,
    tests: [],
    changelog: [{ version: "1.0.0", date: "2026-10-03", note: "Component recipe from the CSSVibes prompt library" }],
  };
}

export const RECIPE_SKILLS: SkillSpec[] = [
  recipe({
    id: "skill.recipe-alerts-messages",
    purpose: "Build alerts, validation messages and inline help that say what happened and what to do next",
    triggers: ["alert", "alerts", "validation message", "error message", "inline help", "warning banner", "status message", "form validation"],
    use: "Form validation, save confirmations, system status, warnings about a section, inline tips.",
    notUse: "Short confirmations that should fade away (use the toast recipe) or explanations of one icon (tooltip recipe).",
    steps: [
      "Use <Notice tone> from src/components/ui: success for done, warning for risk, error for failure, info for tips. Give it a short title and one or two sentences.",
      "Validation: show the message under the field with Field's error prop (it wires aria-describedby and role=alert); validate on blur and on submit, not on every keystroke; keep what the user typed.",
      "Form-level summary: when several fields fail on submit, put one error Notice above the form listing them, and move focus to the first invalid field.",
      "Destructive actions: confirm in a <Dialog> that names the thing, says it can't be undone (or how to undo), with Cancel focused first.",
      "Write the words: what happened, why it matters, what to do. No 'Error', 'Invalid input' or 'Something went wrong' on their own.",
      "Colours only from tokens (--color-success, --color-danger, --color-focus for warning); add an icon or the word so colour isn't the only signal.",
    ],
    edge: "Several errors at once, a server error after valid input, very long messages, a message that must stay until the user acts.",
    done: ["Every error says what to do next", "Errors are announced to screen readers", "No raw colours: Notice tones and tokens only"],
    qa: "Submit the form empty, with one bad field and with a server failure; read each message as a beginner would.",
  }),
  recipe({
    id: "skill.recipe-tooltips",
    purpose: "Add tooltips that explain icons, disabled controls and features without hiding needed information",
    triggers: ["tooltip", "tooltips", "hover hint", "icon explanation", "disabled state explanation", "help hint"],
    use: "Icon-only buttons, toolbar actions, disabled controls that need a reason, short feature hints.",
    notUse: "Anything the user must read to complete a task (put it on the page) or touch-only screens where hover doesn't exist.",
    steps: [
      "Icon-only buttons get an aria-label always; the tooltip repeats that label visually on hover and on keyboard focus.",
      "Build one small Tooltip component next to the building blocks: a wrapper with the trigger, and a bubble with role=tooltip linked by aria-describedby. Show on hover and focus after about 200 ms, hide on blur, mouse leave and Escape.",
      "Style with tokens: --color-text background, --color-surface text, --radius-sm, --text-xs, --space-1/--space-2 padding, a small shadow; position above, flipping below when near the top edge.",
      "Disabled controls: wrap the control so the wrapper takes focus (tabIndex=0) and its tooltip says why it's unavailable and what makes it available.",
      "Keep text to one short sentence; no links or buttons inside a tooltip.",
    ],
    edge: "Tooltips near screen edges, long translated text, touch devices (show the text inline or on tap instead).",
    done: ["Every icon-only button has a label and a tooltip", "Tooltips open on keyboard focus and close with Escape", "Disabled controls explain why"],
    qa: "Tab through the toolbar: each tooltip appears on focus and disappears on Escape; check at 375px.",
  }),
  recipe({
    id: "skill.recipe-toasts",
    purpose: "Show toast messages that confirm actions and report background progress without blocking the screen",
    triggers: ["toast", "toasts", "snackbar", "action feedback", "background process update", "undo message"],
    use: "Confirming a save, delete or send; background tasks finishing; undo for reversible actions.",
    notUse: "Errors the user must fix before continuing (use an inline Notice) or anything needing a decision (use a Dialog).",
    steps: [
      "Build one Toaster: a fixed region bottom-right (bottom-centre on phones) with role=status and aria-live=polite (role=alert for failures), rendered once in App.",
      "Expose a small hook or context: toast({ tone, title, action? }). Tones map to tokens (--color-success, --color-danger, --color-accent).",
      "Auto-dismiss after about 5 seconds; pause while hovered or focused; keep failures until dismissed; include a close button with a label.",
      "Offer Undo for reversible actions (delete, archive) as the toast's action, and actually undo.",
      "Stack at most three; newest on top; animate in with --duration-fast and no motion under prefers-reduced-motion.",
    ],
    edge: "Many toasts at once, the screen changing while a toast shows, a failed Undo.",
    done: ["Saves and deletes confirm with a toast", "Toasts are announced and can be dismissed by keyboard", "Failures stay until dismissed"],
    qa: "Trigger a save, a delete with Undo and a failure; check the screen reader announcement and the 375px layout.",
  }),
  recipe({
    id: "skill.recipe-badges-chips",
    purpose: "Use badges, chips and tags for status, categories, counts and selected filters consistently",
    triggers: ["badge", "badges", "chip", "chips", "tag input", "status label", "filter chips", "selected filters", "notification count", "achievement badge"],
    use: "Statuses in lists and tables, categories, counts on tabs and navigation, selected filters, tag inputs, achievements.",
    notUse: "Primary actions (use Button) or long text (use a Notice).",
    steps: [
      "Status: <Badge tone> with the word (Done, Pending, Failed). Use the same word and tone for the same status everywhere; keep a small map in one file.",
      "Counts: a Badge after the label ('Inbox 12'); include the count in the accessible name; hide zero counts.",
      "Removable chips (selected filters, tags): a button per chip labelled 'Remove <name>', plus 'Clear all'; Backspace in an empty tag input removes the last tag.",
      "Tag input: text field that adds a chip on Enter or comma, ignores duplicates and trims spaces; chips wrap onto new lines.",
      "Achievements: Badge plus an icon and a short reason ('7-day streak'); locked ones say how to earn them.",
      "Only tokens: badge colours from --color-success/--color-danger/--color-accent/--color-text-muted, radius --radius-sm.",
    ],
    edge: "Very long labels (truncate with a title), many chips (wrap, never scroll sideways), unknown status values.",
    done: ["Each status uses one word and tone across the app", "Removable chips have labelled remove buttons", "No colour-only status"],
    qa: "Add and remove tags by keyboard; check statuses read the same in every list.",
  }),
  recipe({
    id: "skill.recipe-cards",
    purpose: "Compose content cards for profiles, bookings, courses, events, settings and onboarding from building blocks",
    triggers: ["profile card", "booking card", "course card", "event card", "onboarding card", "welcome card", "contact card", "settings panel", "portfolio card", "registration card"],
    use: "One item or one group of related information with its actions: a profile, booking, course, event, contact or settings group.",
    notUse: "Whole screens (start from a layout in src/screens) or data that compares across rows (use DataTable).",
    steps: [
      "Use <Card title footer> (or <Card as='li'> inside a list). Body order: the key fact first (name, date, price), then supporting details, then actions in the footer.",
      "One primary Button per card at most; secondary actions as secondary or ghost Buttons.",
      "Profiles and contacts: Avatar, name, role, then contact details as labelled rows; long emails wrap.",
      "Bookings and events: date and time first in a readable format, place, then status Badge, then Change/Cancel actions (Cancel confirms in a Dialog).",
      "Courses: title, short outcome, Progress when started, and Start or Continue.",
      "Onboarding: a welcome card with what to do first, a Checklist of steps and one Continue button; dismissible once done.",
      "Grids of cards use <Grid kind='cards'> so they wrap; whole-card links use one real link or button, not nested clickables.",
    ],
    edge: "Missing images or fields, very long names, an empty list of cards (EmptyState), loading (Skeleton card).",
    done: ["Cards use Card and the building blocks, no one-off borders or shadows", "Each card has at most one primary action", "Empty and loading states exist"],
    qa: "Check a card with every field, one with the minimum, and a list with none, at 375px and 1280px.",
  }),
  recipe({
    id: "skill.recipe-pricing",
    purpose: "Build pricing plans and comparison tables that make the choice clear",
    triggers: ["pricing plans", "plan comparison", "subscription plans", "compare plans", "pricing page", "pricing tiers"],
    use: "Showing plans or product options side by side with prices and features.",
    notUse: "Checkout or payment collection (out of scope for local apps).",
    steps: [
      "Two to four plans in <Grid kind='cards'>; each Card: plan name, price with period ('$12 / month'), one-line who it's for, a feature Checklist, one Button.",
      "Mark the recommended plan with a Badge ('Most popular') and the primary Button; others get secondary Buttons.",
      "Billing switch (monthly/yearly) with a Switch or two-option Tabs; show the saving in words.",
      "Comparison: a DataTable with features as rows and plans as columns; yes/no in words or icons with text.",
      "Prices and features come from one data object, not repeated markup.",
    ],
    edge: "Free plans, custom pricing ('Contact us'), many features (group them), narrow screens (cards stack; table scrolls inside its box).",
    done: ["Each plan shows price, period and who it's for", "One recommended plan", "Comparison readable without colour"],
    qa: "Switch billing period and compare at 375px; confirm one primary button per plan row.",
  }),
  recipe({
    id: "skill.recipe-sign-in",
    purpose: "Build sign-in, sign-up and onboarding forms that are short, clear and forgiving",
    triggers: ["login", "log in", "sign in", "sign-in", "sign up", "signup", "sign-up", "register", "create account", "forgot password"],
    use: "When the spec asks for accounts or a local profile: sign in, create account, forgot password, first-run onboarding.",
    notUse: "Apps the spec says are local-only with no login (use a local profile in Settings instead).",
    steps: [
      "Layout: one centred Card (max width about 26rem) with the product name, an h1 ('Sign in'), the form and a link to the other form; or a split screen with a short product message beside the form on wide screens.",
      "Fields with <Field>: email (type=email, autocomplete=email), password (autocomplete=current-password or new-password) with a Show button; only ask for what's needed.",
      "Errors: say which part is wrong and what to do, without revealing whether an email exists; keep the email typed.",
      "Sign-up: show password rules up front, check them as the user types, and confirm success with the next step.",
      "Onboarding after sign-up: two or three short steps with Progress, Skip available, and the choices saved.",
      "Never store real passwords in plain text or local storage; follow the spec for how accounts work.",
    ],
    edge: "Caps Lock on, paste into password, slow network, already signed in, returning from 'forgot password'.",
    done: ["Fields use correct types and autocomplete", "Errors say what to do next", "Works by keyboard alone"],
    qa: "Sign in with a wrong password, an empty field and correct details by keyboard only; check at 375px.",
  }),
  recipe({
    id: "skill.recipe-gallery",
    purpose: "Build photo and media galleries with a responsive grid and an accessible full-size view",
    triggers: ["gallery", "photo grid", "image grid", "lightbox", "media gallery", "portfolio grid", "exhibition"],
    use: "Collections of images or media: photos, artwork, product shots, portfolio pieces.",
    notUse: "A single hero image or icons.",
    steps: [
      "Grid with CSS grid auto-fill columns (min about 12rem) and gap from --space tokens; images keep their aspect ratio with object-fit and fixed width/height to avoid layout shift.",
      "Every image has meaningful alt text (or alt='' when a caption says the same); captions under images in --text-sm.",
      "Lazy-load below-the-fold images (loading=lazy) with a Skeleton background.",
      "Full-size view in a <Dialog>: the image, caption, Previous/Next buttons, arrow keys, Escape to close, focus returns to the thumbnail.",
      "Filters as chips (badges recipe) and an EmptyState when nothing matches.",
    ],
    edge: "Very tall or wide images, missing images (placeholder with the title), hundreds of items (paginate or load more).",
    done: ["Images have alt text and fixed dimensions", "Full-size view works by keyboard", "Grid reflows at 375px"],
    qa: "Open, step through and close the full-size view by keyboard; check the grid at three widths.",
  }),
  recipe({
    id: "skill.recipe-status-tracking",
    purpose: "Show progress through steps and system status with timelines, status grids and trackers",
    triggers: ["timeline", "order tracking", "tracking", "status grid", "server status", "health monitor", "progress steps", "stepper"],
    use: "Order or delivery tracking, multi-step processes, project status, service health.",
    notUse: "Single numbers (use Stat) or charts over time (dashboard layout).",
    steps: [
      "Timeline: an ordered list; each step has a dot, the step name, its time and a state in words (Done, Current, Next); the current step is marked with aria-current=step.",
      "Stepper for forms: 'Step 2 of 4' text plus Progress; Back and Next buttons; completed steps can be revisited.",
      "Status grid: <Grid kind='stats'> of Cards each with the name, a Badge state and the last update time; the worst state sorts first.",
      "Live updates announce changes politely (role=status) and never move focus.",
      "Colours from tokens; every state also has a word and an icon.",
    ],
    edge: "Skipped or failed steps, unknown status, very long step names, many services.",
    done: ["Every state is written in words", "Current step is marked for screen readers", "Layout works at 375px"],
    qa: "Show each state (done, current, failed, unknown) and read it with colours turned off.",
  }),
  recipe({
    id: "skill.recipe-landing-sections",
    purpose: "Compose landing and about pages from hero, features, proof, team and call-to-action sections",
    triggers: ["landing page", "hero section", "features section", "testimonials", "call to action", "about page", "team section", "marketing page"],
    use: "A product's public front page, an about or mission page, a launch or event page.",
    notUse: "In-app screens a signed-in user works in (use the home or dashboard layouts).",
    steps: [
      "Hero: <Hero> with the promise in the user's words, one primary action and one secondary; an aside with a real product view, not decoration.",
      "Features: three to six items in <Grid kind='cards'>, each a short benefit title and one sentence; icons from the app's icon set.",
      "Proof: testimonials or numbers (Stat) that come from the spec; no invented quotes or logos.",
      "About and team: mission in two sentences, then team Cards with Avatar, name and role.",
      "Close with one call-to-action Section repeating the primary action.",
      "Sections alternate density, use the same heading scale and spacing tokens, and keep one h1.",
    ],
    edge: "No testimonials yet (leave the section out), very long product names, phones (stack every grid).",
    done: ["One h1 and one primary action per page", "No invented proof", "Every section built from building blocks"],
    qa: "Read the page top to bottom at 375px: is the promise and next step clear in the first screen?",
  }),
];
